### ISSUE TITLE
Initiating datasource too slow when defaultDataSource has big amount of tables

### ISSUE THREAD

**Issue by joooohnli** [apache/incubator-shardingsphere#1930]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/sharding-sphere/sharding-sphere/issues).
- Read documentation: [ShardingSphere Doc](http://shardingsphere.io/document/current/en/overview/).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response **more than 7 days** and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
3.1.0
### Which project did you use? Sharding-JDBC or Sharding-Proxy?
Sharding-JDBC
### Expected behavior
init datasource faster
### Actual behavior
init datasource too slow.
### Reason analyze (If you can)
my database has 8000 tables and most of them are sharding tables. it is reasonable to take so long to load metadata of all tables.

io.shardingsphere.core.metadata.table.executor.TableMetaDataInitializer
![image](https://user-images.githubusercontent.com/1615053/53411316-20bac480-3a01-11e9-91cd-5b49ae3765b5.png)

I wonder if metadata of sharding tables that belongs to a same logic table can be load only one time because they are supposed to have same table structure, it would be faster if do so.

### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.
1.  database A has big amount of tables.(in my case, it has 8000 tables)
2. set defaultDataSourceName=A
3. start application
4. initiating lag.(in my case, it took about 10 minutes)

### Example codes for reproduce this issue (such as a github link).

**Comment by terrymanu** [comment]
ShardingSphere need load tables's metadata.
Your default table have big amount of tables, I think same problem occur if other framework need to load metadata, such hibernate.
I tend to don't make this kind of problem as ShardingSphere's problem, what do you think?

**Comment by joooohnli** [comment]
Yes it's not a problem. I just request if an optimization or option can be considered:
metadata of sharding tables that belongs to a same logic table can be loaded only one time because they are supposed to have same table structure

**Comment by daizf** [comment]
I hava the same trouble.
And I think "DefaultTables" should not include ShardingTables. In case default database includes ShardingTables.

**Comment by terrymanu** [comment]
> And I think "DefaultTables" should not include ShardingTables. In case default database includes ShardingTables.

If not include "DefaultTables", use input `show tables` will not display "DefaultTables"

**Comment by daizf** [comment]
I think I have solved it in another way.
Before this, the "ShardingTables" and "DefaultTables" have shared the same database(such as  demodb_00). Now, I separate them with different database.

**Comment by joooohnli** [comment]
Maybe I didn't explain it clearly. let me put it in this way:
Logic table `t` binds sharding tables` t_${0..99}`. while loading metadata, we hope just to load metadata of `t_1`, and set that metadata to rest sharding tables `t_${1..99}`.

**Comment by daizf** [comment]
@joooohnli 
![image](https://user-images.githubusercontent.com/8006592/53538046-1571b100-3b47-11e9-9c9c-6676169b51fa.png)
isCheckingMetaData = false，then just fetch metadata for `t_1`;
And the default value of `isCheckingMetaData` is false.

**Comment by joooohnli** [comment]
@daizf but it will still be load 100 times, so it does not help save time.

**Comment by terrymanu** [comment]
fixed at #1688

**Comment by joooohnli** [comment]
@terrymanu #1688 does not fix my issues.

Time is mainly consumed on metadata loading, not checking.

Based on #1688, the behavior will be like this: metadata of t_1 will be loaded 100 times. it does not save time at all.

**Comment by yjjqrqqq** [comment]
This proplem should not be related to #1688, every boot shardingsphere will scall all tables metadata. too slow~~~~

**Comment by yjjqrqqq** [comment]
Finally, I reloved like this.
I copy TableMetaDataInitializer.java to my own project,, and remove 
`    private Map<String, TableMetaData> loadDefaultTables(final ShardingRule shardingRule) throws SQLException {
        Map<String, TableMetaData> result = new HashMap<>(shardingRule.getTableRules().size(), 1);
        return result;
        /*Optional<String> actualDefaultDataSourceName = shardingRule.findActualDefaultDataSourceName();
        if (actualDefaultDataSourceName.isPresent()) {
            for (String each : getAllTableNames(actualDefaultDataSourceName.get())) {
                result.put(each, tableMetaDataLoader.load(each, shardingRule));
            }
        }
        return result;*/
    }`

I will continue test~~~

**Comment by yjjqrqqq** [comment]
finally,, i reloved like this .

copy TableMetaDataInitializer.java to my project, and removed loadDefaultTables function. then,, times fly~~~

It's not a good idea, but i have no others ways~~

**Comment by linxux** [comment]
> @terrymanu #1688 does not fix my issues.
> 
> Time is mainly consumed on metadata loading, not checking.
> 
> Based on #1688, the behavior will be like this: metadata of t_1 will be loaded 100 times. it does not save time at all.

Agree.
The `loadDefaultTables` still load the table metadata in n times for the same table.

**Comment by MickMo** [comment]
> finally,, i reloved like this .
> 
> copy TableMetaDataInitializer.java to my project, and removed loadDefaultTables function. then,, times fly~~~
> 
> It's not a good idea, but i have no others ways~~

Same problem here ，same way to fix it.

**Comment by yanjunlu** [comment]
> finally,, i reloved like this .
> 
> copy TableMetaDataInitializer.java to my project, and removed loadDefaultTables function. then,, times fly~~~
> 
> It's not a good idea, but i have no others ways~~

Have you found any side effects?

**Comment by jxxyan** [comment]
> > finally,, i reloved like this .
> > copy TableMetaDataInitializer.java to my project, and removed loadDefaultTables function. then,, times fly~~~
> > It's not a good idea, but i have no others ways~~
> 
> Same problem here ，same way to fix it.
> But is there any side effect？



> finally,, i reloved like this .
> 
> copy TableMetaDataInitializer.java to my project, and removed loadDefaultTables function. then,, times fly~~~
> 
> It's not a good idea, but i have no others ways~~

how did you do that ,have some codes?

**Comment by Allkoman** [comment]
https://shardingsphere.apache.org/document/current/en/faq/#18-how-to-speed-up-the-metadata-loading-when-service-starts-up

upgrade to 4.1.0 it's still very slow when I hava 3000 tables

**Comment by Allkoman** [comment]
when I set max.connections.size.per.query = 10000, it's much faster, but it take too much mysql resources as well . neither is ok for me
