### ISSUE TITLE
4.0.0-RC3  Report errors

### ISSUE THREAD

**Issue by xfyang1989** [apache/incubator-shardingsphere#3582]
mysql version:mysql-connector-java-8.0.17.jar
datasource:HikariCP-3.4.1.jar
shardingsphere.version:4.0.0-RC3

Caused by: java.lang.NumberFormatException: For input string: "YES"
	at sun.misc.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:2043)
	at sun.misc.FloatingDecimal.parseDouble(FloatingDecimal.java:110)
	at java.lang.Double.parseDouble(Double.java:538)
	at com.mysql.cj.protocol.a.MysqlTextValueDecoder.getDouble(MysqlTextValueDecoder.java:238)
	at com.mysql.cj.result.BooleanValueFactory.createFromBytes(BooleanValueFactory.java:107)
	at com.mysql.cj.result.BooleanValueFactory.createFromBytes(BooleanValueFactory.java:47)
	at com.mysql.cj.protocol.a.MysqlTextValueDecoder.decodeByteArray(MysqlTextValueDecoder.java:132)
	at com.mysql.cj.protocol.result.AbstractResultsetRow.decodeAndCreateReturnValue(AbstractResultsetRow.java:196)
	at com.mysql.cj.protocol.result.AbstractResultsetRow.getValueFromBytes(AbstractResultsetRow.java:241)
	at com.mysql.cj.protocol.a.result.ByteArrayRow.getValue(ByteArrayRow.java:91)
	at com.mysql.cj.jdbc.result.ResultSetImpl.getObject(ResultSetImpl.java:1270)
	at com.mysql.cj.jdbc.result.ResultSetImpl.getBoolean(ResultSetImpl.java:663)
	at com.mysql.cj.jdbc.result.ResultSetImpl.getBoolean(ResultSetImpl.java:669)
	at com.zaxxer.hikari.pool.HikariProxyResultSet.getBoolean(HikariProxyResultSet.java)
	at org.apache.shardingsphere.core.execute.metadata.TableMetaDataLoader.getColumnMetaDataList(TableMetaDataLoader.java:169)
	at org.apache.shardingsphere.core.execute.metadata.TableMetaDataLoader.createTableMetaData(TableMetaDataLoader.java:147)
	at org.apache.shardingsphere.core.execute.metadata.TableMetaDataLoader.load(TableMetaDataLoader.java:112)
	at org.apache.shardingsphere.core.execute.metadata.TableMetaDataLoader.access$100(TableMetaDataLoader.java:56)
	at org.apache.shardingsphere.core.execute.metadata.TableMetaDataLoader$1.execute(TableMetaDataLoader.java:101)
	at org.apache.shardingsphere.core.execute.ShardingExecuteEngine.syncGroupExecute(ShardingExecuteEngine.java:125)

**Comment by xfyang1989** [comment]
How can I avoid this problem.. It seems to me that someone has asked this question before

**Comment by dongzl** [comment]
Hi @xfyang1989 , This problem have been found by other user and have been fixed by a contributor.

This is the issue: #3503 
This is the fix PR: #3541 

but the code is on dev branch and will be effective in the next release.

if you are interested in ShardingSphere, you can test this problem in dev mode.

if you only want to solve this problem right now, you can downgrade the mysql jdbc jar and try it, e.g. `5.1.x`.

**Comment by xfyang1989** [comment]
OK～

发自我的iPhone

**Comment by yhsmy** [comment]
4.0.0-RC3
I  downgrade the mysql jdbc jar to 5.1.47 & 5.1.18

This error still exists!  @terrymanu @xfyang1989

**Comment by longjy** [comment]
这个下一版本会在什么时候发布呢
